"""empty message

Revision ID: 8765459f22f6
Revises: c1540803ded0
Create Date: 2021-02-22 12:06:33.711510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8765459f22f6'
down_revision = 'c1540803ded0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breed', sa.Column('image_url', sa.String(length=256), nullable=True))
    op.alter_column('breed', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breed', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_column('breed', 'image_url')
    # ### end Alembic commands ###
